# Generated by Django 2.2.6 on 2020-01-21 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='attachments',
            field=models.FileField(max_length=300, null=True, upload_to='attachements/'),
        ),
    ]
