# Generated by Django 2.2.6 on 2020-01-28 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_auto_20200127_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='date_added',
            field=models.DateTimeField(),
        ),
    ]
