# Generated by Django 2.2.6 on 2020-01-28 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_auto_20200128_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='description',
            field=models.TextField(),
        ),
    ]
