# Generated by Django 2.2.6 on 2020-01-28 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0007_auto_20200128_0425'),
    ]

    operations = [
        migrations.CreateModel(
            name='attachments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='attachments/')),
            ],
            options={
                'verbose_name': 'attachments',
                'verbose_name_plural': 'attachmentss',
            },
        ),
    ]
