# Generated by Django 2.2.6 on 2020-01-28 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0008_attachments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='attachments',
            new_name='Attachment',
        ),
        migrations.AlterModelOptions(
            name='attachment',
            options={'verbose_name': 'Attachment', 'verbose_name_plural': 'Attachments'},
        ),
        migrations.RemoveField(
            model_name='case',
            name='attachments',
        ),
    ]
