# Generated by Django 2.2.6 on 2020-01-28 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0009_auto_20200128_0743'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='attachments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cases.Attachment'),
        ),
    ]
