# Generated by Django 2.2.6 on 2020-01-28 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0011_remove_case_attachments'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(upload_to='attachments/')),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cases.Case')),
            ],
            options={
                'verbose_name': 'Case File',
                'verbose_name_plural': 'Case Files',
            },
        ),
        migrations.DeleteModel(
            name='Attachment',
        ),
    ]
