# Generated by Django 2.2.6 on 2020-02-09 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0012_auto_20200128_0901'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriorityLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'PriorityLevel',
                'verbose_name_plural': 'PriorityLevels',
            },
        ),
        migrations.CreateModel(
            name='CaseTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('date_modefied', models.DateTimeField(auto_now=True)),
                ('deadline', models.DateTimeField()),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.Case')),
            ],
            options={
                'verbose_name': 'Case Task',
                'verbose_name_plural': 'Case Tasks',
            },
        ),
    ]
