# Generated by Django 2.2.6 on 2020-02-09 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0013_casetask_prioritylevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='casetask',
            name='priority_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cases.PriorityLevel'),
        ),
    ]
