# Generated by Django 2.2.6 on 2020-02-09 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0014_casetask_priority_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='court',
            field=models.CharField(default='District Court', max_length=250),
        ),
    ]
