# Generated by Django 2.2.6 on 2020-02-18 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0016_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='casefile',
            name='title',
            field=models.CharField(default='', max_length=250),
        ),
    ]
