# Generated by Django 2.2.6 on 2020-02-18 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0017_casefile_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casefile',
            old_name='files',
            new_name='file',
        ),
    ]
