# Generated by Django 2.2.6 on 2020-02-18 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0018_auto_20200218_0455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casefile',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.Case'),
        ),
    ]
