# Generated by Django 2.2.6 on 2020-02-19 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0009_auto_20200213_0832'),
        ('cases', '0019_auto_20200218_0540'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseArchives',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_archived', models.DateTimeField()),
                ('date_modefied', models.DateTimeField(auto_now=True)),
                ('archived_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lawyers.OtherStaff')),
                ('case', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cases.Case')),
            ],
            options={
                'verbose_name': 'CaseArchives',
                'verbose_name_plural': 'CaseArchivess',
            },
        ),
    ]
