# Generated by Django 2.2.6 on 2020-02-19 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0009_auto_20200213_0832'),
        ('cases', '0020_casearchives'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CaseArchives',
            new_name='CaseArchive',
        ),
        migrations.AlterModelOptions(
            name='casearchive',
            options={'verbose_name': 'CaseArchives', 'verbose_name_plural': 'CaseArchives'},
        ),
    ]
