# Generated by Django 2.2.6 on 2020-02-19 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0021_auto_20200218_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casearchive',
            name='date_archived',
        ),
    ]
