# Generated by Django 2.2.6 on 2020-02-19 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0022_remove_casearchive_date_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='casearchive',
            name='archive_location',
            field=models.CharField(default='Archives', max_length=250),
        ),
    ]
