# Generated by Django 2.2.6 on 2020-02-21 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0023_casearchive_archive_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Authority',
                'verbose_name_plural': 'Authorities',
            },
        ),
        migrations.CreateModel(
            name='Principles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principle', models.CharField(max_length=350)),
                ('authority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.Authority')),
            ],
            options={
                'verbose_name': 'Principles',
                'verbose_name_plural': 'Principless',
            },
        ),
        migrations.CreateModel(
            name='LegalArgument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('argument', models.CharField(max_length=350)),
                ('authorities', models.TextField()),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.Case')),
            ],
            options={
                'verbose_name': 'LegalArgument',
                'verbose_name_plural': 'LegalArguments',
            },
        ),
    ]
