# Generated by Django 2.2.6 on 2020-02-21 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0024_authority_legalargument_principles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='principles',
            name='authority',
        ),
        migrations.AlterField(
            model_name='legalargument',
            name='argument',
            field=models.CharField(max_length=350, unique=True),
        ),
        migrations.DeleteModel(
            name='Authority',
        ),
        migrations.DeleteModel(
            name='Principles',
        ),
    ]
