# Generated by Django 2.2.6 on 2020-02-25 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0025_auto_20200221_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='date_added',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
