# Generated by Django 2.2.6 on 2020-02-25 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0026_category_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='casefile',
            name='date_added',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
