# Generated by Django 2.2.6 on 2020-02-25 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0027_casefile_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='casetask',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
