# Generated by Django 2.2.6 on 2020-03-10 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0030_case_closed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('date_modified', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Courts',
                'verbose_name_plural': 'Courts',
            },
        ),
        migrations.AlterField(
            model_name='case',
            name='court',
            field=models.CharField(default='', max_length=250),
        ),
    ]
