# Generated by Django 2.2.6 on 2020-03-10 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0031_auto_20200310_0358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='court',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cases.Court'),
        ),
    ]
