# Generated by Django 2.2.6 on 2020-03-10 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0032_auto_20200310_0401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='court',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
