# Generated by Django 2.2 on 2020-05-07 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0036_courtsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='case_number',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='court_number',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
