# Generated by Django 2.2.6 on 2020-03-04 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcategory',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
