# Generated by Django 2.2.6 on 2020-02-22 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authority',
            name='date_added',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
