# Generated by Django 2.2.6 on 2020-02-22 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principles', '0003_principles_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='principles',
            name='date_add',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
