# Generated by Django 2.2.6 on 2020-01-21 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lawyers', '0007_auto_20200114_0348'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Document Status',
                'verbose_name_plural': 'Document Statuss',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_added', models.DateTimeField()),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.DocumentStatus')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
            },
        ),
        migrations.CreateModel(
            name='AccessedDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_accessed', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='lawyers.OtherStaff')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='documents.Document')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lawyers.Lawyer')),
            ],
            options={
                'verbose_name': 'AccessedDocument',
                'verbose_name_plural': 'AccessedDocuments',
            },
        ),
    ]
