# Generated by Django 2.2.6 on 2020-01-21 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_auto_20200121_0728'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentrecord',
            options={'verbose_name': 'AccessedDocument', 'verbose_name_plural': 'Document Records'},
        ),
    ]
