# Generated by Django 2.2.6 on 2020-01-29 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_auto_20200121_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='storage_location',
            field=models.CharField(default='room 1', max_length=50),
        ),
    ]
