# Generated by Django 2.2.6 on 2020-01-30 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_document_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='documents.DocumentStatus'),
        ),
    ]
