# Generated by Django 2.2.6 on 2020-02-03 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_auto_20200130_0229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentrecord',
            old_name='date_accessed',
            new_name='date_approved',
        ),
        migrations.AddField(
            model_name='document',
            name='description',
            field=models.CharField(default='Document Description', max_length=550),
        ),
        migrations.AddField(
            model_name='documentrecord',
            name='date_requested',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='documentrecord',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='lawyers.OtherStaff'),
        ),
    ]
