# Generated by Django 2.2.6 on 2020-02-04 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_auto_20200203_0337'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrecord',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
