# Generated by Django 2.2.6 on 2020-02-18 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0012_documentrecord_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentArchive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.CharField(max_length=350)),
                ('description', models.TextField()),
                ('date_added', models.DateTimeField()),
                ('status', models.CharField(max_length=350)),
                ('category', models.CharField(max_length=350)),
                ('added_by', models.CharField(max_length=250)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'DocumentArchive',
                'verbose_name_plural': 'DocumentArchives',
            },
        ),
        migrations.CreateModel(
            name='RequestArchive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.CharField(max_length=350)),
                ('description', models.TextField()),
                ('date_added', models.DateTimeField()),
                ('status', models.CharField(max_length=350)),
                ('category', models.CharField(max_length=350)),
                ('added_by', models.CharField(max_length=350)),
                ('requested_by', models.CharField(max_length=350, null=True)),
                ('date_requested', models.DateTimeField(auto_now=True)),
                ('date_approved', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'RequestArchive',
                'verbose_name_plural': 'RequestArchives',
            },
        ),
    ]
