# Generated by Django 2.2.6 on 2020-02-18 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0013_documentarchive_requestarchive'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentarchive',
            name='location',
            field=models.CharField(default='Archives', max_length=250),
            preserve_default=False,
        ),
    ]
