# Generated by Django 2.2.6 on 2020-02-18 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0014_documentarchive_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestarchive',
            name='approved_by',
            field=models.CharField(default='', max_length=250),
        ),
    ]
