# Generated by Django 2.2.6 on 2020-02-25 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0015_requestarchive_approved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='shelf_number',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
