# Generated by Django 2.2.6 on 2020-03-05 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0030_case_closed'),
        ('documents', '0017_auto_20200304_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cases.Case'),
        ),
    ]
