# Generated by Django 2.2.6 on 2020-03-05 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0018_document_case'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='files',
        ),
    ]
