# Generated by Django 2.2.6 on 2020-03-05 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0020_docfile_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='docfile',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
