# Generated by Django 2.2.6 on 2020-04-26 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0003_auto_20200426_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Will',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_execution', models.DateTimeField()),
                ('date_deposited', models.DateTimeField()),
                ('receipt_number', models.CharField(max_length=250)),
                ('court', models.CharField(max_length=250)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.Client')),
            ],
            options={
                'verbose_name': 'Will',
                'verbose_name_plural': 'Wills',
            },
        ),
    ]
