# Generated by Django 2.2.6 on 2020-04-27 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wills', '0002_will_last_edited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='will',
            name='court',
        ),
        migrations.AddField(
            model_name='will',
            name='internal_depository',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
