# Generated by Django 2.2.6 on 2020-04-27 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wills', '0003_auto_20200427_0148'),
    ]

    operations = [
        migrations.AddField(
            model_name='will',
            name='court',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
