# Generated by Django 2.2.6 on 2020-04-28 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wills', '0005_will_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgreementCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Agreement Category',
                'verbose_name_plural': 'Agreement Categories',
            },
        ),
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parties', models.CharField(max_length=250)),
                ('date_of_execution', models.DateTimeField()),
                ('date_of_registration', models.DateTimeField()),
                ('internal_depository', models.CharField(max_length=250)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wills.AgreementCategory')),
            ],
            options={
                'verbose_name': 'Agreement',
                'verbose_name_plural': 'Agreements',
            },
        ),
    ]
