# Generated by Django 2.2 on 2020-05-06 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wills', '0009_auto_20200501_2231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='will',
            name='client',
        ),
    ]
