# Generated by Django 2.2 on 2020-05-06 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20200426_1309'),
        ('wills', '0010_remove_will_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='will',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.Client'),
        ),
    ]
