# Generated by Django 2.2 on 2020-05-06 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wills', '0011_will_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agreement',
            name='category',
        ),
    ]
