# Generated by Django 2.2 on 2020-05-07 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wills', '0013_agreement_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='date_of_execution',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='will',
            name='date_of_execution',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
