# Generated by Django 2.2 on 2020-05-14 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0012_auto_20200422_2333'),
        ('wills', '0014_auto_20200507_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='will',
            name='user',
        ),
        migrations.AddField(
            model_name='will',
            name='lawyer',
            field=models.ManyToManyField(to='lawyers.Lawyer'),
        ),
    ]
