# Generated by Django 2.2.6 on 2020-01-08 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyer',
            name='lawyer_status',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lawyers.LawyerStatus'),
        ),
    ]
