# Generated by Django 2.2.6 on 2020-01-13 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0003_auto_20200108_0821'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otherstaff',
            options={'verbose_name': 'OtherStaff', 'verbose_name_plural': 'OtherStaff'},
        ),
    ]
