# Generated by Django 2.2.6 on 2020-01-14 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0004_auto_20200113_0115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_other_staff',
        ),
    ]
