# Generated by Django 2.2.6 on 2020-01-14 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0005_remove_user_is_other_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyer',
            name='bar_number',
            field=models.IntegerField(unique=True),
        ),
    ]
