# Generated by Django 2.2.6 on 2020-02-20 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0009_auto_20200213_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default='024 412 3456', max_length=50),
        ),
    ]
