# Generated by Django 2.2.6 on 2020-03-05 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0010_auto_20200220_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Office Manager'), (2, 'Front Desk'), (3, 'secretary')], primary_key=True, serialize=False),
        ),
    ]
