# Generated by Django 2.2 on 2020-04-22 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0011_auto_20200305_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/avatar.jpg', null=True, upload_to='avatars/'),
        ),
    ]
