# Generated by Django 2.2.6 on 2020-03-08 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
